### ISSUE TITLE
[3.1] Column Name Mapping Issue

### ISSUE THREAD

**Issue by zpqrtbnk** [schotime/NPoco#242] opened 2016-03-14 14:37 UTC
If a column is defined as
~~~~
[Column("foo")]
public int Bar { get; set; }
~~~~
When auto-select is enabled, the generated SQL looks like `SELECT foo AS Bar FROM ...` and `PropertyMapper.FindMember` will find the column, because the corresponding `PocoMember` name is "Bar" and the data reader field's name is "Bar" too.

However, as soon as manual SQL is written, neither `SELECT * FROM ...` nor `SELECT foo FROM ...` work because the `PocoMember` name is still "Bar" but the data reader field's name is "foo"... and the `PocoColumn.ColumnAlias` is empty. So, `FindMember` does not find the member.

Practically, this means that `SELECT *` cannot work at all, and any custom SQL _must_ remember to add the `AS Bar` bit. Which is not really convenient. In addition, the following will fail, _even with auto-select_.
~~~~
[Column("foo")]
public int Bar { get; set; }
[Column("bar")]
public int Foo { get; set; }
~~~~
Indeed, auto-select will do `SELECT foo AS Bar, bar AS Foo FROM ...`, the reader's first field will be named "Bar" which will be mapped to property `Bar` instead of `Foo`. Of course one answer is... don't do it ;-) But...

Couldn't the situation be improved with:
* Queries (and that includes auto-select) do _not_ alias a column unless an alias is specified explicitely for that column
* `FindMember` is modified with:
~~~~
return pocoMembers.FirstOrDefault(x => 
{
  var col = x.PocoColumn;

  if (col != null) // if we have a column, match against the alias if any, else the name
    return IsEqual(name, col.ColumnAlias ?? col.ColumnName);

  return IsEqual(name, x.Name); // else use member's name
});
~~~~

Is this all making any sense to you?

**Comment by zpqrtbnk** [comment] 2016-03-14 15:07
And... that would not be enough, now `BuildMapPlans` would need to be modified to begin with:
~~~~
// find pocomember by property name
var pocoMember = pocoMembers.FirstOrDefault(x => IsEqual(groupedName.Item, x.Name));
~~~~
So `FindMember` is used _only_ when mapping from old to new conventions, and it has to work as described above, and then it's not needed anymore and everything can happen on name only. But `FindMember` should not be used in both cases else it causes confusion.

**Comment by dwirawan** [comment] 2016-03-14 15:55
hey, @zpqrtbnk @schotime i think the problem is the difference between property and column name in ``PropertyMapper.FindMember``, i don't know if it is intended, therefore there is ``ColumnAlias`` to accomodate this, but here is my fix in ``PropertyMapper.FindMember``

```
return pocoMembers.FirstOrDefault(x => IsEqual(name, x.Name) || (x.PocoColumn != null && (IsEqual(name, x.PocoColumn.ColumnName) || IsEqual(name, x.PocoColumn.ColumnAlias))));
```

**Comment by zpqrtbnk** [comment] 2016-03-14 15:58
@dwirawan I tried this too but as long as you leave the initial `IsEqual(name, x.Name)` you cannot handle the mixed foo/bar columns and aliases from my example. `FindMember` needs to be splitted into two, one method that deals with database names and aliases (when converting from "old conventions") and _not_ names, and another method that deals with names.

**Comment by dwirawan** [comment] 2016-03-14 16:00
@zpqrtbnk ahh yess, i forgot that.. well, i agree with you, it should look for ``ColumnName`` or ``ColumnAlias`` first, and fallback to default property name :+1:

**Comment by schotime** [comment] 2016-03-14 22:21
hmmm.... @zpqrtbnk you're changes created 10 test failures, and if you use FindMember with your changes in both spots you get 50 test failures. double hmmmm

**Comment by schotime** [comment] 2016-03-14 23:31
This seemed to make it work.

```csharp
            return pocoMembers
                .Where(x => x.ReferenceType == ReferenceType.None)
                .FirstOrDefault(x =>
                {
                    var col = x.PocoColumn;

                    if (col != null && IsEqual(name, col.ColumnAlias ?? col.ColumnName))
                        return true;

                    return IsEqual(name, x.Name);
                });
```

**Comment by schotime** [comment] 2016-03-15 02:55
Fixed in latest commit.

**Closed** 2016-03-21 23:57 UTC
