### ISSUE TITLE
Fetch and FetchOneToMany will skip VersionColumn if a complete SQL statement is provided

### ISSUE THREAD

**Issue by dampee** [schotime/NPoco#523] opened 2018-12-28 22:52 UTC
## Setup
I have a simple table with one record. I have a normal Dto with one property.

    [TableName("MyTable")]
    [PrimaryKey("Uid")]
    public class MyTableDto
    {
        [Column("Uid")]
        public Guid? Uid { get; set; }

        [VersionColumn("Timestamp", VersionColumnType.RowVersion)]
        public byte[] Timestamp{ get; set; }

## Issue

A Fetch (and FetchOneToMany also)

    Db.Fetch<MyTableDto>("SELECT * FROM myTable WHERE blabla ")[0].Timestamp

return **NULL** on the version column. Which is wrong.  The timestamp column is not null!
But when I remove the SELECT from the SQL:

    Db.Fetch<MyTableDto>("FROM myTable WHERE blabla ")[0].Timestamp 

it returns the version column

    {byte[8]}
      [0]: 0
      [1]: 0
      [2]: 0
      [3]: 0
      ...

I tried to [reproduce this on a separate repo, but I failed](https://github.com/dampee/npoco-test). 

Could someone please:

1) explain me what is going on?
2) help me to debug?
3) tell me it is not my fault?

**Comment by schotime** [comment] 2019-05-23 23:36
That is bizarre, but you said you can't reproduce it either. 
There seems to be no code specifically targeting version columns either.
Closing for now, reopen if something pops up.

**Closed by schotime** 2019-05-23 23:36 UTC
